### ISSUE TITLE
Try in IDX fails

### ISSUE THREAD

**Issue by domesticmouse** [flutter/ai#15]
Clicking on the "Try in IDX" button results in the following failure. Please fix.

<img width="629" alt="Screenshot 2024-12-07 at 10 09 48 am" src="https://github.com/user-attachments/assets/8b7d04e8-dd68-42e2-808f-f730206e3c35">

**Comment by rodydavis** [comment]
Will do! Also the template works now since it is public!

**Comment by rodydavis** [comment]
Looking into it!

**Comment by rodydavis** [comment]
Fixed: https://github.com/flutter/ai/pull/23

Not sure why this was broken, we use this pattern on other templates

**Comment by rodydavis** [comment]
Template creates correctly now and Flutter version is getting updated

**Comment by domesticmouse** [comment]
Closing as fixed
