### ISSUE TITLE
Any plan to support to chatgpt?

### ISSUE THREAD

**Issue by LaiZhou** [flutter/ai#28]
Any plan to support to chatgpt?

**Comment by csells** [comment]
ChatGPT is a chat app built around the LLM API provided by OpenAI. @domesticmouse and I are working with @davidmigloz on support for OpenAI LLMs right now (among others): https://github.com/flutter/ai/pull/30

**Comment by bernaferrari** [comment]
I wonder how that is going to work without leaking your OpenAI keys in the app. On web there is NextJS which separates server and app, but I don't think anyone did that on Flutter yet...

**Comment by csells** [comment]
You can certainly build your own server-side proxy and plug that into the AI Toolkit.

**Comment by bernaferrari** [comment]
Maybe you could have that somewhere in AI Toolkit, because it feels like a very common request for people (without that, they can't use the AI Toolkit in production)

**Comment by csells** [comment]
You certainly can. Vertex has support for that.

**Comment by bernaferrari** [comment]
But Vertex doesn't support OpenAI

**Comment by davidmigloz** [comment]
You can build a simple proxy as @csells was mentioning, eg. using [Firebase Cloud Functions](https://github.com/alfianlosari/firebase-openai-proxy/blob/main/openai-proxy/functions/src/index.ts).

**Comment by DominikStarke** [comment]
I've created a minimal open-webui api client as LlmProvider implementation.
I'm currently using it with ollama (local model), but since open-webui also supports chat-gpt it should be possible to use it as well.

``` dart
LlmChatView(
  provider: OpenwebuiProvider(
    host: 'http://127.0.0.1:3000', /// Open-webui host
    model: 'llama3.1:latest', /// The chat-model you want to use, for example gpt-4o-mini, 
    apiKey: "YOUR_API_KEY", /// Open-webui api key, not the api key of external llm provider,
    history: [] /// Previous conversation
  ),
)
```

The fork can be found [here](https://github.com/DominikStarke/flutter_ai_toolkit)

**Comment by csells** [comment]
hey, @DominikStarke. if you want to contribute [your open-webui provider](https://github.com/DominikStarke/flutter_ai_toolkit/blob/main/lib/src/providers/implementations/openwebui_provider.dart), you can do so into the 
[flutter_ai_community](https://github.com/davidmigloz/flutter_ai_community) repo that @davidmigloz and I are pulling together.
