### ISSUE TITLE
[Feature] Adding Input Audio Streaming Provider (S2T + VAD)

### ISSUE THREAD

**Issue by fvisticot** [flutter/ai#35]
Is it possible to add a SpeechToText AudioStreaming provider as an input of the "Audio recording" button ?
It would be fine to plug different S2T audio provider and a Voice Activity Detection (VAD)

**Comment by csells** [comment]
May I ask what problem you're trying to solve?

**Comment by fvisticot** [comment]
- User click on the record button or User Voice is detected to start the recording
- Audio recording starts 
- Audio Streaming is sent to a local or distant SpeechToText Engine 
   - Local could be : https://github.com/huggingface/transformers.js-examples/tree/main/moonshine-web using WASM
   - Distant could be any SpeechToText Engine
 - User clicks on Stop or "Silence" is detected 
 - Current text (from stream) is ready to be sent as text for the LLM input prompt

**Comment by csells** [comment]
How is that different from what happens now?

**Comment by fvisticot** [comment]
If I'm correct, the current implementation starts audio recording when clicking on the record button and the audio is available as a binary file as an input attachement when clicking on "Send" button.
The attachement is send to the LLMProvider as an input (audio).

If I'm using another custom LLMProvider and that LLM does not take audio as an input, I need to "SpeechToText" the recording audio before sending the Text (from Audio) to the LLM.

**Comment by csells** [comment]
The behavior is as you are hoping for - the audio is translated and turned into text for the user to edit. It's not provided as an audio file when the user presses the Submit button. Give it a try. See what you think .

**Comment by fvisticot** [comment]
I gived a try using the EchoProvider and my own LLM provider implementation.
With the EchoProvider I get the following image. Text is not extracted from audio

<img width="503" alt="image" src="https://github.com/user-attachments/assets/5ce75ad9-b516-4d57-95cc-ac30f8134f8e" />


With my own provider, the sendMessageStream method is fired with the following inputs:
- Prompt: translate the attached audio to text; provide the result of that translation as just the text of the translation itself. be careful to separate the background audio from the foreground audio and only provide the result of translating the foreground audio.
- attachments: 1 Audio file

**Comment by csells** [comment]
Is it sendMessageStream being called to translate the audio or generateStream? It should be the latter.

**Comment by fvisticot** [comment]
generateStream.

Did you confirm I need to use my own audio translation library/code in the generateStream method if I'M NOT USING the google_generative_ai package (this package is doing the audio translation ?) ?

**Comment by csells** [comment]
The way the chat works is that it uses the provider's generateStream implementation to translate audio. So far I haven't noticed a large latency that requires streaming the audio.

**Comment by fvisticot** [comment]
Tx a lot for the details.
It means we should use the same model for Audio2Text and running the Inference on the question ?
Do you think it could be possible to decouple the 2 actions ?

**Comment by csells** [comment]
You can do that today with your own custom provider that forwards to your model of choice.
