### ISSUE TITLE
feature: Context Caching for Gemini Provider

### ISSUE THREAD

**Issue by ONLYstcm** [flutter/ai#36]
I'm exploring the flutter/ai package and would like to understand how to implement Context Caching for specific content as described in the [Gemini API documentation](https://ai.google.dev/gemini-api/docs/caching). I want to optimize token usage by caching repeated context or static content while generating responses dynamically for user-specific inputs. However, the documentation doesn't explicitly describe how this can be integrated with Flutter's AI package.

**Comment by csells** [comment]
What would the scenario be here?

**Comment by ONLYstcm** [comment]
I have a document which serve as the main source of information for all of the user prompts. I want all the user prompts to be based on the document. In the vertex studio, by instructing the system to only look at the context provided, I was sort of able to achieve this. Rather than feeding this document for each user prompt I was investigating if there's an alternative and more optimised approach since several users will be using the same document (single main source of information)

**Comment by csells** [comment]
Can you share some example code that shows what you have in mind?

**Comment by ONLYstcm** [comment]
I think this snippet in the Gemini docs should best describe it - https://ai.google.dev/gemini-api/docs/caching?lang=python#generate-content

**Comment by ONLYstcm** [comment]
After looking into it a bit more, content caching would need to be implemented in the model declaration under `generative-ai-dart`. There's already an issue to track it - https://github.com/google-gemini/generative-ai-dart/issues/187
